#pragma once

#include <string_view>
#include <vtz/tz_reader/link.h>

namespace vtz {
    // Disabled because we don't want code to be changed after generation
    // clang-format off

    /// Contains a list of known timezone names. Used to construct timezone
    /// cache if the timezone source files cannot be found.
    constexpr std::string_view KNOWN_ZONES[] {
        "Africa/Abidjan",
        "Africa/Algiers",
        "Africa/Bissau",
        "Africa/Cairo",
        "Africa/Casablanca",
        "Africa/Ceuta",
        "Africa/El_Aaiun",
        "Africa/Johannesburg",
        "Africa/Juba",
        "Africa/Khartoum",
        "Africa/Lagos",
        "Africa/Maputo",
        "Africa/Monrovia",
        "Africa/Nairobi",
        "Africa/Ndjamena",
        "Africa/Sao_Tome",
        "Africa/Tripoli",
        "Africa/Tunis",
        "Africa/Windhoek",
        "America/Adak",
        "America/Anchorage",
        "America/Araguaina",
        "America/Argentina/Buenos_Aires",
        "America/Argentina/Catamarca",
        "America/Argentina/Cordoba",
        "America/Argentina/Jujuy",
        "America/Argentina/La_Rioja",
        "America/Argentina/Mendoza",
        "America/Argentina/Rio_Gallegos",
        "America/Argentina/Salta",
        "America/Argentina/San_Juan",
        "America/Argentina/San_Luis",
        "America/Argentina/Tucuman",
        "America/Argentina/Ushuaia",
        "America/Asuncion",
        "America/Bahia",
        "America/Bahia_Banderas",
        "America/Barbados",
        "America/Belem",
        "America/Belize",
        "America/Boa_Vista",
        "America/Bogota",
        "America/Boise",
        "America/Cambridge_Bay",
        "America/Campo_Grande",
        "America/Cancun",
        "America/Caracas",
        "America/Cayenne",
        "America/Chicago",
        "America/Chihuahua",
        "America/Ciudad_Juarez",
        "America/Costa_Rica",
        "America/Coyhaique",
        "America/Cuiaba",
        "America/Danmarkshavn",
        "America/Dawson",
        "America/Dawson_Creek",
        "America/Denver",
        "America/Detroit",
        "America/Edmonton",
        "America/Eirunepe",
        "America/El_Salvador",
        "America/Fort_Nelson",
        "America/Fortaleza",
        "America/Glace_Bay",
        "America/Goose_Bay",
        "America/Grand_Turk",
        "America/Guatemala",
        "America/Guayaquil",
        "America/Guyana",
        "America/Halifax",
        "America/Havana",
        "America/Hermosillo",
        "America/Indiana/Indianapolis",
        "America/Indiana/Knox",
        "America/Indiana/Marengo",
        "America/Indiana/Petersburg",
        "America/Indiana/Tell_City",
        "America/Indiana/Vevay",
        "America/Indiana/Vincennes",
        "America/Indiana/Winamac",
        "America/Inuvik",
        "America/Iqaluit",
        "America/Jamaica",
        "America/Juneau",
        "America/Kentucky/Louisville",
        "America/Kentucky/Monticello",
        "America/La_Paz",
        "America/Lima",
        "America/Los_Angeles",
        "America/Maceio",
        "America/Managua",
        "America/Manaus",
        "America/Martinique",
        "America/Matamoros",
        "America/Mazatlan",
        "America/Menominee",
        "America/Merida",
        "America/Metlakatla",
        "America/Mexico_City",
        "America/Miquelon",
        "America/Moncton",
        "America/Monterrey",
        "America/Montevideo",
        "America/New_York",
        "America/Nome",
        "America/Noronha",
        "America/North_Dakota/Beulah",
        "America/North_Dakota/Center",
        "America/North_Dakota/New_Salem",
        "America/Nuuk",
        "America/Ojinaga",
        "America/Panama",
        "America/Paramaribo",
        "America/Phoenix",
        "America/Port-au-Prince",
        "America/Porto_Velho",
        "America/Puerto_Rico",
        "America/Punta_Arenas",
        "America/Rankin_Inlet",
        "America/Recife",
        "America/Regina",
        "America/Resolute",
        "America/Rio_Branco",
        "America/Santarem",
        "America/Santiago",
        "America/Santo_Domingo",
        "America/Sao_Paulo",
        "America/Scoresbysund",
        "America/Sitka",
        "America/St_Johns",
        "America/Swift_Current",
        "America/Tegucigalpa",
        "America/Thule",
        "America/Tijuana",
        "America/Toronto",
        "America/Vancouver",
        "America/Whitehorse",
        "America/Winnipeg",
        "America/Yakutat",
        "Antarctica/Casey",
        "Antarctica/Davis",
        "Antarctica/Macquarie",
        "Antarctica/Mawson",
        "Antarctica/Palmer",
        "Antarctica/Rothera",
        "Antarctica/Troll",
        "Antarctica/Vostok",
        "Asia/Almaty",
        "Asia/Amman",
        "Asia/Anadyr",
        "Asia/Aqtau",
        "Asia/Aqtobe",
        "Asia/Ashgabat",
        "Asia/Atyrau",
        "Asia/Baghdad",
        "Asia/Baku",
        "Asia/Bangkok",
        "Asia/Barnaul",
        "Asia/Beirut",
        "Asia/Bishkek",
        "Asia/Chita",
        "Asia/Colombo",
        "Asia/Damascus",
        "Asia/Dhaka",
        "Asia/Dili",
        "Asia/Dubai",
        "Asia/Dushanbe",
        "Asia/Famagusta",
        "Asia/Gaza",
        "Asia/Hebron",
        "Asia/Ho_Chi_Minh",
        "Asia/Hong_Kong",
        "Asia/Hovd",
        "Asia/Irkutsk",
        "Asia/Jakarta",
        "Asia/Jayapura",
        "Asia/Jerusalem",
        "Asia/Kabul",
        "Asia/Kamchatka",
        "Asia/Karachi",
        "Asia/Kathmandu",
        "Asia/Khandyga",
        "Asia/Kolkata",
        "Asia/Krasnoyarsk",
        "Asia/Kuching",
        "Asia/Macau",
        "Asia/Magadan",
        "Asia/Makassar",
        "Asia/Manila",
        "Asia/Nicosia",
        "Asia/Novokuznetsk",
        "Asia/Novosibirsk",
        "Asia/Omsk",
        "Asia/Oral",
        "Asia/Pontianak",
        "Asia/Pyongyang",
        "Asia/Qatar",
        "Asia/Qostanay",
        "Asia/Qyzylorda",
        "Asia/Riyadh",
        "Asia/Sakhalin",
        "Asia/Samarkand",
        "Asia/Seoul",
        "Asia/Shanghai",
        "Asia/Singapore",
        "Asia/Srednekolymsk",
        "Asia/Taipei",
        "Asia/Tashkent",
        "Asia/Tbilisi",
        "Asia/Tehran",
        "Asia/Thimphu",
        "Asia/Tokyo",
        "Asia/Tomsk",
        "Asia/Ulaanbaatar",
        "Asia/Urumqi",
        "Asia/Ust-Nera",
        "Asia/Vladivostok",
        "Asia/Yakutsk",
        "Asia/Yangon",
        "Asia/Yekaterinburg",
        "Asia/Yerevan",
        "Atlantic/Azores",
        "Atlantic/Bermuda",
        "Atlantic/Canary",
        "Atlantic/Cape_Verde",
        "Atlantic/Faroe",
        "Atlantic/Madeira",
        "Atlantic/South_Georgia",
        "Atlantic/Stanley",
        "Australia/Adelaide",
        "Australia/Brisbane",
        "Australia/Broken_Hill",
        "Australia/Darwin",
        "Australia/Eucla",
        "Australia/Hobart",
        "Australia/Lindeman",
        "Australia/Lord_Howe",
        "Australia/Melbourne",
        "Australia/Perth",
        "Australia/Sydney",
        "Etc/GMT",
        "Etc/GMT+1",
        "Etc/GMT+10",
        "Etc/GMT+11",
        "Etc/GMT+12",
        "Etc/GMT+2",
        "Etc/GMT+3",
        "Etc/GMT+4",
        "Etc/GMT+5",
        "Etc/GMT+6",
        "Etc/GMT+7",
        "Etc/GMT+8",
        "Etc/GMT+9",
        "Etc/GMT-1",
        "Etc/GMT-10",
        "Etc/GMT-11",
        "Etc/GMT-12",
        "Etc/GMT-13",
        "Etc/GMT-14",
        "Etc/GMT-2",
        "Etc/GMT-3",
        "Etc/GMT-4",
        "Etc/GMT-5",
        "Etc/GMT-6",
        "Etc/GMT-7",
        "Etc/GMT-8",
        "Etc/GMT-9",
        "Etc/UTC",
        "Europe/Andorra",
        "Europe/Astrakhan",
        "Europe/Athens",
        "Europe/Belgrade",
        "Europe/Berlin",
        "Europe/Brussels",
        "Europe/Bucharest",
        "Europe/Budapest",
        "Europe/Chisinau",
        "Europe/Dublin",
        "Europe/Gibraltar",
        "Europe/Helsinki",
        "Europe/Istanbul",
        "Europe/Kaliningrad",
        "Europe/Kirov",
        "Europe/Kyiv",
        "Europe/Lisbon",
        "Europe/London",
        "Europe/Madrid",
        "Europe/Malta",
        "Europe/Minsk",
        "Europe/Moscow",
        "Europe/Paris",
        "Europe/Prague",
        "Europe/Riga",
        "Europe/Rome",
        "Europe/Samara",
        "Europe/Saratov",
        "Europe/Simferopol",
        "Europe/Sofia",
        "Europe/Tallinn",
        "Europe/Tirane",
        "Europe/Ulyanovsk",
        "Europe/Vienna",
        "Europe/Vilnius",
        "Europe/Volgograd",
        "Europe/Warsaw",
        "Europe/Zurich",
        "Factory",
        "Indian/Chagos",
        "Indian/Maldives",
        "Indian/Mauritius",
        "Pacific/Apia",
        "Pacific/Auckland",
        "Pacific/Bougainville",
        "Pacific/Chatham",
        "Pacific/Easter",
        "Pacific/Efate",
        "Pacific/Fakaofo",
        "Pacific/Fiji",
        "Pacific/Galapagos",
        "Pacific/Gambier",
        "Pacific/Guadalcanal",
        "Pacific/Guam",
        "Pacific/Honolulu",
        "Pacific/Kanton",
        "Pacific/Kiritimati",
        "Pacific/Kosrae",
        "Pacific/Kwajalein",
        "Pacific/Marquesas",
        "Pacific/Nauru",
        "Pacific/Niue",
        "Pacific/Norfolk",
        "Pacific/Noumea",
        "Pacific/Pago_Pago",
        "Pacific/Palau",
        "Pacific/Pitcairn",
        "Pacific/Port_Moresby",
        "Pacific/Rarotonga",
        "Pacific/Tahiti",
        "Pacific/Tarawa",
        "Pacific/Tongatapu",
    };

    /// contains a list of known links. Used to construct the timezone link
    /// cache if the timezone source files cannot be found.
    constexpr zone_link KNOWN_LINKS[] {
        zone_link{ "Etc/GMT", "GMT" },
        zone_link{ "Australia/Sydney", "Australia/ACT" },
        zone_link{ "Australia/Lord_Howe", "Australia/LHI" },
        zone_link{ "Australia/Sydney", "Australia/NSW" },
        zone_link{ "Australia/Darwin", "Australia/North" },
        zone_link{ "Australia/Brisbane", "Australia/Queensland" },
        zone_link{ "Australia/Adelaide", "Australia/South" },
        zone_link{ "Australia/Hobart", "Australia/Tasmania" },
        zone_link{ "Australia/Melbourne", "Australia/Victoria" },
        zone_link{ "Australia/Perth", "Australia/West" },
        zone_link{ "Australia/Broken_Hill", "Australia/Yancowinna" },
        zone_link{ "America/Rio_Branco", "Brazil/Acre" },
        zone_link{ "America/Noronha", "Brazil/DeNoronha" },
        zone_link{ "America/Sao_Paulo", "Brazil/East" },
        zone_link{ "America/Manaus", "Brazil/West" },
        zone_link{ "Europe/Brussels", "CET" },
        zone_link{ "America/Chicago", "CST6CDT" },
        zone_link{ "America/Halifax", "Canada/Atlantic" },
        zone_link{ "America/Winnipeg", "Canada/Central" },
        zone_link{ "America/Toronto", "Canada/Eastern" },
        zone_link{ "America/Edmonton", "Canada/Mountain" },
        zone_link{ "America/St_Johns", "Canada/Newfoundland" },
        zone_link{ "America/Vancouver", "Canada/Pacific" },
        zone_link{ "America/Regina", "Canada/Saskatchewan" },
        zone_link{ "America/Whitehorse", "Canada/Yukon" },
        zone_link{ "America/Santiago", "Chile/Continental" },
        zone_link{ "Pacific/Easter", "Chile/EasterIsland" },
        zone_link{ "America/Havana", "Cuba" },
        zone_link{ "Europe/Athens", "EET" },
        zone_link{ "America/Panama", "EST" },
        zone_link{ "America/New_York", "EST5EDT" },
        zone_link{ "Africa/Cairo", "Egypt" },
        zone_link{ "Europe/Dublin", "Eire" },
        zone_link{ "Etc/GMT", "Etc/GMT+0" },
        zone_link{ "Etc/GMT", "Etc/GMT-0" },
        zone_link{ "Etc/GMT", "Etc/GMT0" },
        zone_link{ "Etc/GMT", "Etc/Greenwich" },
        zone_link{ "Etc/UTC", "Etc/UCT" },
        zone_link{ "Etc/UTC", "Etc/Universal" },
        zone_link{ "Etc/UTC", "Etc/Zulu" },
        zone_link{ "Europe/London", "GB" },
        zone_link{ "Europe/London", "GB-Eire" },
        zone_link{ "Etc/GMT", "GMT+0" },
        zone_link{ "Etc/GMT", "GMT-0" },
        zone_link{ "Etc/GMT", "GMT0" },
        zone_link{ "Etc/GMT", "Greenwich" },
        zone_link{ "Asia/Hong_Kong", "Hongkong" },
        zone_link{ "Africa/Abidjan", "Iceland" },
        zone_link{ "Asia/Tehran", "Iran" },
        zone_link{ "Asia/Jerusalem", "Israel" },
        zone_link{ "America/Jamaica", "Jamaica" },
        zone_link{ "Asia/Tokyo", "Japan" },
        zone_link{ "Pacific/Kwajalein", "Kwajalein" },
        zone_link{ "Africa/Tripoli", "Libya" },
        zone_link{ "Europe/Brussels", "MET" },
        zone_link{ "America/Phoenix", "MST" },
        zone_link{ "America/Denver", "MST7MDT" },
        zone_link{ "America/Tijuana", "Mexico/BajaNorte" },
        zone_link{ "America/Mazatlan", "Mexico/BajaSur" },
        zone_link{ "America/Mexico_City", "Mexico/General" },
        zone_link{ "Pacific/Auckland", "NZ" },
        zone_link{ "Pacific/Chatham", "NZ-CHAT" },
        zone_link{ "America/Denver", "Navajo" },
        zone_link{ "Asia/Shanghai", "PRC" },
        zone_link{ "Europe/Warsaw", "Poland" },
        zone_link{ "Europe/Lisbon", "Portugal" },
        zone_link{ "Asia/Taipei", "ROC" },
        zone_link{ "Asia/Seoul", "ROK" },
        zone_link{ "Asia/Singapore", "Singapore" },
        zone_link{ "Europe/Istanbul", "Turkey" },
        zone_link{ "Etc/UTC", "UCT" },
        zone_link{ "America/Anchorage", "US/Alaska" },
        zone_link{ "America/Adak", "US/Aleutian" },
        zone_link{ "America/Phoenix", "US/Arizona" },
        zone_link{ "America/Chicago", "US/Central" },
        zone_link{ "America/Indiana/Indianapolis", "US/East-Indiana" },
        zone_link{ "America/New_York", "US/Eastern" },
        zone_link{ "Pacific/Honolulu", "US/Hawaii" },
        zone_link{ "America/Indiana/Knox", "US/Indiana-Starke" },
        zone_link{ "America/Detroit", "US/Michigan" },
        zone_link{ "America/Denver", "US/Mountain" },
        zone_link{ "America/Los_Angeles", "US/Pacific" },
        zone_link{ "Pacific/Pago_Pago", "US/Samoa" },
        zone_link{ "Etc/UTC", "UTC" },
        zone_link{ "Etc/UTC", "Universal" },
        zone_link{ "Europe/Moscow", "W-SU" },
        zone_link{ "Etc/UTC", "Zulu" },
        zone_link{ "America/Argentina/Buenos_Aires", "America/Buenos_Aires" },
        zone_link{ "America/Argentina/Catamarca", "America/Catamarca" },
        zone_link{ "America/Argentina/Cordoba", "America/Cordoba" },
        zone_link{ "America/Indiana/Indianapolis", "America/Indianapolis" },
        zone_link{ "America/Argentina/Jujuy", "America/Jujuy" },
        zone_link{ "America/Indiana/Knox", "America/Knox_IN" },
        zone_link{ "America/Kentucky/Louisville", "America/Louisville" },
        zone_link{ "America/Argentina/Mendoza", "America/Mendoza" },
        zone_link{ "America/Puerto_Rico", "America/Virgin" },
        zone_link{ "Pacific/Pago_Pago", "Pacific/Samoa" },
        zone_link{ "Africa/Abidjan", "Africa/Accra" },
        zone_link{ "Africa/Nairobi", "Africa/Addis_Ababa" },
        zone_link{ "Africa/Nairobi", "Africa/Asmara" },
        zone_link{ "Africa/Abidjan", "Africa/Bamako" },
        zone_link{ "Africa/Lagos", "Africa/Bangui" },
        zone_link{ "Africa/Abidjan", "Africa/Banjul" },
        zone_link{ "Africa/Maputo", "Africa/Blantyre" },
        zone_link{ "Africa/Lagos", "Africa/Brazzaville" },
        zone_link{ "Africa/Maputo", "Africa/Bujumbura" },
        zone_link{ "Africa/Abidjan", "Africa/Conakry" },
        zone_link{ "Africa/Abidjan", "Africa/Dakar" },
        zone_link{ "Africa/Nairobi", "Africa/Dar_es_Salaam" },
        zone_link{ "Africa/Nairobi", "Africa/Djibouti" },
        zone_link{ "Africa/Lagos", "Africa/Douala" },
        zone_link{ "Africa/Abidjan", "Africa/Freetown" },
        zone_link{ "Africa/Maputo", "Africa/Gaborone" },
        zone_link{ "Africa/Maputo", "Africa/Harare" },
        zone_link{ "Africa/Nairobi", "Africa/Kampala" },
        zone_link{ "Africa/Maputo", "Africa/Kigali" },
        zone_link{ "Africa/Lagos", "Africa/Kinshasa" },
        zone_link{ "Africa/Lagos", "Africa/Libreville" },
        zone_link{ "Africa/Abidjan", "Africa/Lome" },
        zone_link{ "Africa/Lagos", "Africa/Luanda" },
        zone_link{ "Africa/Maputo", "Africa/Lubumbashi" },
        zone_link{ "Africa/Maputo", "Africa/Lusaka" },
        zone_link{ "Africa/Lagos", "Africa/Malabo" },
        zone_link{ "Africa/Johannesburg", "Africa/Maseru" },
        zone_link{ "Africa/Johannesburg", "Africa/Mbabane" },
        zone_link{ "Africa/Nairobi", "Africa/Mogadishu" },
        zone_link{ "Africa/Lagos", "Africa/Niamey" },
        zone_link{ "Africa/Abidjan", "Africa/Nouakchott" },
        zone_link{ "Africa/Abidjan", "Africa/Ouagadougou" },
        zone_link{ "Africa/Lagos", "Africa/Porto-Novo" },
        zone_link{ "America/Puerto_Rico", "America/Anguilla" },
        zone_link{ "America/Puerto_Rico", "America/Antigua" },
        zone_link{ "America/Puerto_Rico", "America/Aruba" },
        zone_link{ "America/Panama", "America/Atikokan" },
        zone_link{ "America/Puerto_Rico", "America/Blanc-Sablon" },
        zone_link{ "America/Panama", "America/Cayman" },
        zone_link{ "America/Phoenix", "America/Creston" },
        zone_link{ "America/Puerto_Rico", "America/Curacao" },
        zone_link{ "America/Puerto_Rico", "America/Dominica" },
        zone_link{ "America/Puerto_Rico", "America/Grenada" },
        zone_link{ "America/Puerto_Rico", "America/Guadeloupe" },
        zone_link{ "America/Puerto_Rico", "America/Kralendijk" },
        zone_link{ "America/Puerto_Rico", "America/Lower_Princes" },
        zone_link{ "America/Puerto_Rico", "America/Marigot" },
        zone_link{ "America/Puerto_Rico", "America/Montserrat" },
        zone_link{ "America/Toronto", "America/Nassau" },
        zone_link{ "America/Puerto_Rico", "America/Port_of_Spain" },
        zone_link{ "America/Puerto_Rico", "America/St_Barthelemy" },
        zone_link{ "America/Puerto_Rico", "America/St_Kitts" },
        zone_link{ "America/Puerto_Rico", "America/St_Lucia" },
        zone_link{ "America/Puerto_Rico", "America/St_Thomas" },
        zone_link{ "America/Puerto_Rico", "America/St_Vincent" },
        zone_link{ "America/Puerto_Rico", "America/Tortola" },
        zone_link{ "Pacific/Port_Moresby", "Antarctica/DumontDUrville" },
        zone_link{ "Pacific/Auckland", "Antarctica/McMurdo" },
        zone_link{ "Asia/Riyadh", "Antarctica/Syowa" },
        zone_link{ "Europe/Berlin", "Arctic/Longyearbyen" },
        zone_link{ "Asia/Riyadh", "Asia/Aden" },
        zone_link{ "Asia/Qatar", "Asia/Bahrain" },
        zone_link{ "Asia/Kuching", "Asia/Brunei" },
        zone_link{ "Asia/Singapore", "Asia/Kuala_Lumpur" },
        zone_link{ "Asia/Riyadh", "Asia/Kuwait" },
        zone_link{ "Asia/Dubai", "Asia/Muscat" },
        zone_link{ "Asia/Bangkok", "Asia/Phnom_Penh" },
        zone_link{ "Asia/Bangkok", "Asia/Vientiane" },
        zone_link{ "Africa/Abidjan", "Atlantic/Reykjavik" },
        zone_link{ "Africa/Abidjan", "Atlantic/St_Helena" },
        zone_link{ "Europe/Brussels", "Europe/Amsterdam" },
        zone_link{ "Europe/Prague", "Europe/Bratislava" },
        zone_link{ "Europe/Zurich", "Europe/Busingen" },
        zone_link{ "Europe/Berlin", "Europe/Copenhagen" },
        zone_link{ "Europe/London", "Europe/Guernsey" },
        zone_link{ "Europe/London", "Europe/Isle_of_Man" },
        zone_link{ "Europe/London", "Europe/Jersey" },
        zone_link{ "Europe/Belgrade", "Europe/Ljubljana" },
        zone_link{ "Europe/Brussels", "Europe/Luxembourg" },
        zone_link{ "Europe/Helsinki", "Europe/Mariehamn" },
        zone_link{ "Europe/Paris", "Europe/Monaco" },
        zone_link{ "Europe/Berlin", "Europe/Oslo" },
        zone_link{ "Europe/Belgrade", "Europe/Podgorica" },
        zone_link{ "Europe/Rome", "Europe/San_Marino" },
        zone_link{ "Europe/Belgrade", "Europe/Sarajevo" },
        zone_link{ "Europe/Belgrade", "Europe/Skopje" },
        zone_link{ "Europe/Berlin", "Europe/Stockholm" },
        zone_link{ "Europe/Zurich", "Europe/Vaduz" },
        zone_link{ "Europe/Rome", "Europe/Vatican" },
        zone_link{ "Europe/Belgrade", "Europe/Zagreb" },
        zone_link{ "Africa/Nairobi", "Indian/Antananarivo" },
        zone_link{ "Asia/Bangkok", "Indian/Christmas" },
        zone_link{ "Asia/Yangon", "Indian/Cocos" },
        zone_link{ "Africa/Nairobi", "Indian/Comoro" },
        zone_link{ "Indian/Maldives", "Indian/Kerguelen" },
        zone_link{ "Asia/Dubai", "Indian/Mahe" },
        zone_link{ "Africa/Nairobi", "Indian/Mayotte" },
        zone_link{ "Asia/Dubai", "Indian/Reunion" },
        zone_link{ "Pacific/Port_Moresby", "Pacific/Chuuk" },
        zone_link{ "Pacific/Tarawa", "Pacific/Funafuti" },
        zone_link{ "Pacific/Tarawa", "Pacific/Majuro" },
        zone_link{ "Pacific/Pago_Pago", "Pacific/Midway" },
        zone_link{ "Pacific/Guadalcanal", "Pacific/Pohnpei" },
        zone_link{ "Pacific/Guam", "Pacific/Saipan" },
        zone_link{ "Pacific/Tarawa", "Pacific/Wake" },
        zone_link{ "Pacific/Tarawa", "Pacific/Wallis" },
        zone_link{ "Africa/Abidjan", "Africa/Timbuktu" },
        zone_link{ "America/Argentina/Catamarca", "America/Argentina/ComodRivadavia" },
        zone_link{ "America/Adak", "America/Atka" },
        zone_link{ "America/Panama", "America/Coral_Harbour" },
        zone_link{ "America/Tijuana", "America/Ensenada" },
        zone_link{ "America/Indiana/Indianapolis", "America/Fort_Wayne" },
        zone_link{ "America/Toronto", "America/Montreal" },
        zone_link{ "America/Toronto", "America/Nipigon" },
        zone_link{ "America/Iqaluit", "America/Pangnirtung" },
        zone_link{ "America/Rio_Branco", "America/Porto_Acre" },
        zone_link{ "America/Winnipeg", "America/Rainy_River" },
        zone_link{ "America/Argentina/Cordoba", "America/Rosario" },
        zone_link{ "America/Tijuana", "America/Santa_Isabel" },
        zone_link{ "America/Denver", "America/Shiprock" },
        zone_link{ "America/Toronto", "America/Thunder_Bay" },
        zone_link{ "America/Edmonton", "America/Yellowknife" },
        zone_link{ "Pacific/Auckland", "Antarctica/South_Pole" },
        zone_link{ "Asia/Ulaanbaatar", "Asia/Choibalsan" },
        zone_link{ "Asia/Shanghai", "Asia/Chongqing" },
        zone_link{ "Asia/Shanghai", "Asia/Harbin" },
        zone_link{ "Asia/Urumqi", "Asia/Kashgar" },
        zone_link{ "Asia/Jerusalem", "Asia/Tel_Aviv" },
        zone_link{ "Europe/Berlin", "Atlantic/Jan_Mayen" },
        zone_link{ "Australia/Sydney", "Australia/Canberra" },
        zone_link{ "Australia/Hobart", "Australia/Currie" },
        zone_link{ "Europe/London", "Europe/Belfast" },
        zone_link{ "Europe/Chisinau", "Europe/Tiraspol" },
        zone_link{ "Europe/Kyiv", "Europe/Uzhgorod" },
        zone_link{ "Europe/Kyiv", "Europe/Zaporozhye" },
        zone_link{ "Pacific/Kanton", "Pacific/Enderbury" },
        zone_link{ "Pacific/Honolulu", "Pacific/Johnston" },
        zone_link{ "Pacific/Port_Moresby", "Pacific/Yap" },
        zone_link{ "Europe/Lisbon", "WET" },
        zone_link{ "Africa/Nairobi", "Africa/Asmera" },
        zone_link{ "America/Nuuk", "America/Godthab" },
        zone_link{ "Asia/Ashgabat", "Asia/Ashkhabad" },
        zone_link{ "Asia/Kolkata", "Asia/Calcutta" },
        zone_link{ "Asia/Shanghai", "Asia/Chungking" },
        zone_link{ "Asia/Dhaka", "Asia/Dacca" },
        zone_link{ "Europe/Istanbul", "Asia/Istanbul" },
        zone_link{ "Asia/Kathmandu", "Asia/Katmandu" },
        zone_link{ "Asia/Macau", "Asia/Macao" },
        zone_link{ "Asia/Yangon", "Asia/Rangoon" },
        zone_link{ "Asia/Ho_Chi_Minh", "Asia/Saigon" },
        zone_link{ "Asia/Thimphu", "Asia/Thimbu" },
        zone_link{ "Asia/Makassar", "Asia/Ujung_Pandang" },
        zone_link{ "Asia/Ulaanbaatar", "Asia/Ulan_Bator" },
        zone_link{ "Atlantic/Faroe", "Atlantic/Faeroe" },
        zone_link{ "Europe/Kyiv", "Europe/Kiev" },
        zone_link{ "Asia/Nicosia", "Europe/Nicosia" },
        zone_link{ "Pacific/Honolulu", "HST" },
        zone_link{ "America/Los_Angeles", "PST8PDT" },
        zone_link{ "Pacific/Guadalcanal", "Pacific/Ponape" },
        zone_link{ "Pacific/Port_Moresby", "Pacific/Truk" },
    };

    // clang-format on
} // namespace vtz
